# Generated by Django 4.2.8 on 2024-04-03 09:27

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="News",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_published",
                    models.BooleanField(
                        default=True,
                        help_text="Снимите галочку, чтобы скрыть публикацию.",
                        verbose_name="Опубликовано",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Добавлено"),
                ),
                ("title", models.CharField(max_length=256, verbose_name="Заголовок")),
                ("text", models.TextField(verbose_name="Текст")),
                (
                    "image",
                    models.ImageField(
                        default=None,
                        null=True,
                        upload_to="news/images/",
                        verbose_name="Картинка",
                    ),
                ),
                (
                    "video",
                    models.FileField(
                        blank=True,
                        default=None,
                        null=True,
                        upload_to="videos_uploaded",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=["MOV", "avi", "mp4", "webm", "mkv"]
                            )
                        ],
                        verbose_name="Видео",
                    ),
                ),
                (
                    "pub_date",
                    models.DateTimeField(
                        default=datetime.datetime(2024, 4, 3, 12, 27, 2, 42888),
                        help_text="Если установить дату и время в будущем — можно делать отложенные публикации.",
                        verbose_name="Дата и время публикации",
                    ),
                ),
            ],
            options={
                "verbose_name": "Новость",
                "verbose_name_plural": "Новости",
            },
        ),
        migrations.CreateModel(
            name="Poll",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_published",
                    models.BooleanField(
                        default=True,
                        help_text="Снимите галочку, чтобы скрыть публикацию.",
                        verbose_name="Опубликовано",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Добавлено"),
                ),
                (
                    "question_text",
                    models.CharField(max_length=256, verbose_name="Текст опроса"),
                ),
            ],
            options={
                "verbose_name": "Опрос",
                "verbose_name_plural": "Опросы",
            },
        ),
        migrations.CreateModel(
            name="Choice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "choice_text",
                    models.CharField(max_length=256, verbose_name="Текст вопроса"),
                ),
                ("votes", models.IntegerField(default=0, verbose_name="Число голосов")),
                (
                    "poll",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="choices",
                        to="homepage.poll",
                        verbose_name="Опрос",
                    ),
                ),
            ],
            options={
                "verbose_name": "Вариант опроса",
                "verbose_name_plural": "Варианты опроса",
            },
        ),
    ]
