# Generated by Django 4.2.8 on 2024-04-08 16:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("homepage", "0003_alter_news_pub_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="news",
            name="pub_date",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 4, 8, 19, 7, 39, 177155),
                help_text="Если установить дату и время в будущем — можно делать отложенные публикации.",
                verbose_name="Дата и время публикации",
            ),
        ),
    ]
