# Generated by Django 4.2.8 on 2024-04-08 17:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("homepage", "0004_alter_news_pub_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="poll",
            name="pub_date",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 4, 8, 20, 19, 34, 292437),
                help_text="Если установить дату и время в будущем — можно делать отложенные публикации.",
                verbose_name="Дата и время публикации",
            ),
        ),
        migrations.AlterField(
            model_name="news",
            name="pub_date",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 4, 8, 20, 19, 34, 292437),
                help_text="Если установить дату и время в будущем — можно делать отложенные публикации.",
                verbose_name="Дата и время публикации",
            ),
        ),
    ]
