# Generated by Django 4.2.8 on 2024-05-17 06:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("homepage", "0021_alter_poll_pub_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="poll",
            name="is_anonymous",
            field=models.BooleanField(default=False, verbose_name="Анонимный опрос"),
        ),
        migrations.AddField(
            model_name="poll",
            name="is_multiple_choice",
            field=models.BooleanField(
                default=False, verbose_name="Несколько вариантов ответа"
            ),
        ),
        migrations.AlterField(
            model_name="poll",
            name="pub_date",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 5, 17, 9, 21, 54, 418657),
                help_text="Если установить дату и время в будущем — можно делать отложенные публикации.",
                verbose_name="Дата и время публикации",
            ),
        ),
    ]
