# Generated by Django 4.2.8 on 2024-06-05 11:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("homepage", "0024_alter_poll_pub_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="news",
            name="pub_date",
            field=models.DateTimeField(
                default=django.utils.timezone.now,
                help_text="Если установить дату и время в будущем — можно делать отложенные публикации.",
                verbose_name="Дата и время публикации",
            ),
        ),
        migrations.AlterField(
            model_name="poll",
            name="pub_date",
            field=models.DateTimeField(
                default=django.utils.timezone.now,
                help_text="Если установить дату и время в будущем — можно делать отложенные публикации.",
                verbose_name="Дата и время публикации",
            ),
        ),
    ]
