version: '3'

volumes:
  static:
  media:

services:
  backend:
    build: ./backend/
    env_file: ./.env
    volumes:
      - static:/backend_static
      - media:/media

  gateway:
    build: ./gateway/
    env_file: ./.env
    volumes:
      - static:/staticfiles
      - media:/media
    ports:
      - 8000:80
