version: '3'

volumes:
  pg_data:
  static:
  media:

services:
  db:
    image: postgres:13
    env_file: ./backend/.env
    volumes:
      - pg_data:/var/lib/postgresql/data
  backend:
    build: ./backend/
    env_file: ./backend/.env
    volumes:
      - static:/backend_static
      - media:/media

  gateway:
    build: ./gateway/
    env_file: ./backend/.env
    volumes:
      - static:/staticfiles
      - media:/media
    ports:
      - 8000:80
