version: '3'

volumes:
  pg_data:
  static:
  media:

services:
  db:
    image: postgres:13
    env_file: ./backend/.env
    volumes:
      - pg_data:/var/lib/postgresql/data
  backend_test:
    build: ./backend/
    env_file: ./backend/.env
    volumes:
      - static:/app/collected_static/
      - media:/media/

  gateway_test:
    build: ./gateway/
    env_file: ./backend/.env
    volumes:
      - static:/staticfiles
      - media:/media
    ports:
      - 8082:80
