# Generated by Django 4.2.18 on 2025-03-17 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conference',
            name='file',
            field=models.CharField(blank=True, default=None, null=True, verbose_name='Документ'),
        ),
        migrations.AlterField(
            model_name='course',
            name='file',
            field=models.CharField(blank=True, default=None, null=True, verbose_name='Документ'),
        ),
        migrations.AlterField(
            model_name='diploma',
            name='file',
            field=models.CharField(blank=True, default=None, null=True, verbose_name='Документ'),
        ),
        migrations.AlterField(
            model_name='hobby',
            name='file',
            field=models.CharField(blank=True, default=None, null=True, verbose_name='Документ'),
        ),
        migrations.AlterField(
            model_name='performance',
            name='file',
            field=models.CharField(blank=True, default=None, null=True, verbose_name='Документ'),
        ),
        migrations.AlterField(
            model_name='reward',
            name='file',
            field=models.CharField(blank=True, default=None, null=True, verbose_name='Документ'),
        ),
        migrations.AlterField(
            model_name='sport',
            name='file',
            field=models.CharField(blank=True, default=None, null=True, verbose_name='Документ'),
        ),
        migrations.AlterField(
            model_name='training',
            name='file',
            field=models.CharField(blank=True, default=None, null=True, verbose_name='Документ'),
        ),
        migrations.AlterField(
            model_name='university',
            name='file',
            field=models.CharField(blank=True, default=None, null=True, verbose_name='Документ'),
        ),
        migrations.AlterField(
            model_name='victory',
            name='file',
            field=models.CharField(blank=True, default=None, null=True, verbose_name='Документ'),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='file',
            field=models.CharField(blank=True, default=None, null=True, verbose_name='Документ'),
        ),
    ]
