# Generated by Django 4.2.8 on 2024-04-25 12:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_remove_employee_organization_alter_conference_image_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='structuralsubdivision',
            options={'verbose_name': 'структурное подразделение', 'verbose_name_plural': 'структурные подразделения'},
        ),
        migrations.RemoveField(
            model_name='organization',
            name='structural_division',
        ),
        migrations.AddField(
            model_name='structuralsubdivision',
            name='organization',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='structural_subdivisions', to='employees.organization', verbose_name='Организация'),
            preserve_default=False,
        ),
    ]
