# Generated by Django 4.2.18 on 2025-04-16 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_alter_conference_file_alter_course_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='sex',
            field=models.CharField(blank=True, choices=[('Не указан', 'Не указан'), ('Мужской', 'Мужской'), ('Женский', 'Женский')], default='Не указан', max_length=16, null=True, verbose_name='Пол'),
        ),
    ]
