# Generated by Django 4.2.18 on 2025-04-16 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_employee_sex'),
    ]

    operations = [
        migrations.AddField(
            model_name='training',
            name='year',
            field=models.IntegerField(blank=True, null=True, verbose_name='Год повышения квалификации'),
        ),
    ]
