# Generated by Django 4.2.18 on 2025-04-16 08:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0004_training_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='head',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='is_org_head', to=settings.AUTH_USER_MODEL, verbose_name='Руководитель организации'),
        ),
        migrations.AddField(
            model_name='structuralsubdivision',
            name='chief',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='is_chief', to=settings.AUTH_USER_MODEL, verbose_name='Руководитель подразделения'),
        ),
    ]
