# Generated by Django 4.2.8 on 2024-04-26 08:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0005_characteristic_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='career',
            name='characteristic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='employees.characteristic', verbose_name='Сотрудник'),
        ),
        migrations.AlterField(
            model_name='competence',
            name='characteristic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='employees.characteristic', verbose_name='Сотрудник'),
        ),
        migrations.AlterField(
            model_name='course',
            name='characteristic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='employees.characteristic', verbose_name='Сотрудник'),
        ),
    ]
