# Generated by Django 4.2.18 on 2025-04-16 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0005_organization_head_structuralsubdivision_chief'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='competence',
            name='characteristic',
        ),
        migrations.AddField(
            model_name='competence',
            name='characteristic',
            field=models.ManyToManyField(blank=True, related_name='%(class)ss', to='employees.characteristic', verbose_name='Сотрудник'),
        ),
    ]
