# Generated by Django 4.2.18 on 2025-04-25 12:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0006_remove_competence_characteristic_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='structuralsubdivision',
            name='supervisor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='is_supervisor', to=settings.AUTH_USER_MODEL, verbose_name='Супервайзор подразделения'),
        ),
    ]