# Generated by Django 4.2.18 on 2025-05-13 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0007_structuralsubdivision_supervisor'),
    ]

    operations = [
        migrations.AddField(
            model_name='competence',
            name='is_important',
            field=models.BooleanField(default=False, help_text='Указывает, была ли эта компетенция определена администратором как важный навык.', verbose_name='Важный навык'),
        ),
        migrations.AlterField(
            model_name='characteristic',
            name='about',
            field=models.TextField(blank=True, max_length=1024, verbose_name='Обо мне'),
        ),
        migrations.AlterField(
            model_name='characteristic',
            name='experience',
            field=models.CharField(blank=True, max_length=256, verbose_name='Стаж работы'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='inner_telephone_number',
            field=models.CharField(blank=True, max_length=12, null=True, verbose_name='Внутренний номер телефона'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='office',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Кабинет'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='telephone_number',
            field=models.CharField(blank=True, max_length=12, null=True, verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='university',
            name='faculty',
            field=models.CharField(blank=True, max_length=256, verbose_name='Факультет'),
        ),
    ]
