# Generated by Django 4.2.8 on 2024-04-26 16:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0007_alter_conference_characteristic_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='structural_division',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='employees.structuralsubdivision', verbose_name='Структурное подразделение'),
        ),
    ]
