# Generated by Django 4.2.18 on 2025-07-02 20:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0008_competence_is_important_alter_characteristic_about_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Дата оценки'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rating',
            name='text',
            field=models.TextField(blank=True, help_text='Текст, поясняющий оценку (необязательно)', null=True, verbose_name='Комментарий'),
        ),
    ]
