# Generated by Django 4.2.8 on 2024-05-26 13:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0008_alter_employee_structural_division'),
    ]

    operations = [
        migrations.AlterField(
            model_name='characteristic',
            name='avatar',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='', verbose_name='Аватар'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='structural_division',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='positions', to='employees.structuralsubdivision', verbose_name='Структурное подразделение'),
        ),
    ]
