# Generated by Django 4.2.8 on 2024-05-30 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0009_alter_characteristic_avatar_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='job_title',
            field=models.CharField(blank=True, choices=[('Разработчик', 'Разработчик'), ('Руководитель', 'Руководитель'), ('Тестировщик', 'Тестировщик')], max_length=256, null=True, verbose_name='Должность'),
        ),
    ]
