# Generated by Django 4.2.8 on 2024-06-05 11:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("employees", "0010_alter_employee_job_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="characteristic",
            name="avatar",
            field=models.ImageField(
                blank=True,
                default=None,
                null=True,
                upload_to="employees/avatars/",
                verbose_name="Аватар",
            ),
        ),
        migrations.AlterField(
            model_name="conference",
            name="image",
            field=models.ImageField(
                default=None,
                null=True,
                upload_to="employees/%(class)s/",
                verbose_name="Картинка",
            ),
        ),
        migrations.AlterField(
            model_name="hobby",
            name="image",
            field=models.ImageField(
                default=None,
                null=True,
                upload_to="employees/%(class)s/",
                verbose_name="Картинка",
            ),
        ),
        migrations.AlterField(
            model_name="performance",
            name="image",
            field=models.ImageField(
                default=None,
                null=True,
                upload_to="employees/%(class)s/",
                verbose_name="Картинка",
            ),
        ),
        migrations.AlterField(
            model_name="reward",
            name="image",
            field=models.ImageField(
                default=None,
                null=True,
                upload_to="employees/%(class)s/",
                verbose_name="Картинка",
            ),
        ),
        migrations.AlterField(
            model_name="sport",
            name="image",
            field=models.ImageField(
                default=None,
                null=True,
                upload_to="employees/%(class)s/",
                verbose_name="Картинка",
            ),
        ),
        migrations.AlterField(
            model_name="training",
            name="image",
            field=models.ImageField(
                default=None,
                null=True,
                upload_to="employees/%(class)s/",
                verbose_name="Картинка",
            ),
        ),
        migrations.AlterField(
            model_name="victory",
            name="image",
            field=models.ImageField(
                default=None,
                null=True,
                upload_to="employees/%(class)s/",
                verbose_name="Картинка",
            ),
        ),
        migrations.AlterField(
            model_name="volunteer",
            name="image",
            field=models.ImageField(
                default=None,
                null=True,
                upload_to="employees/%(class)s/",
                verbose_name="Картинка",
            ),
        ),
    ]
