# Generated by Django 4.2.18 on 2025-08-27 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0010_idea'),
    ]

    operations = [
        migrations.AddField(
            model_name='idea',
            name='resolution',
            field=models.TextField(blank=True, null=True, verbose_name='Решение'),
        ),
        migrations.AddField(
            model_name='idea',
            name='status',
            field=models.CharField(choices=[('Получено', 'Получено'), ('Одобрено', 'Одобрено'), ('Отклонено', 'Отклонено'), ('На рассмотрении', 'На рассмотрении')], default='Получено', max_length=20, verbose_name='Статус'),
        ),
    ]
