# Generated by Django 4.2.18 on 2025-09-11 16:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0011_idea_resolution_idea_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Segment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Название')),
                ('url', models.URLField(blank=True, default='', verbose_name='Ссылка')),
                ('description', models.TextField(blank=True, default='', verbose_name='Описание')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('supervisor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supervised_segments', to=settings.AUTH_USER_MODEL, verbose_name='Ответственный')),
            ],
            options={
                'verbose_name': 'Сегмент',
                'verbose_name_plural': 'Сегменты',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='FavoriteSegment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления в избранное')),
                ('segment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='employees.segment', verbose_name='Сегмент')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_segments', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Избранный сегмент',
                'verbose_name_plural': 'Избранные сегменты',
                'ordering': ['-created_at'],
                'unique_together': {('user', 'segment')},
            },
        ),
    ]
