# Generated by Django 4.2.18 on 2025-09-25 15:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0012_segment_favoritesegment'),
    ]

    operations = [
        migrations.CreateModel(
            name='SegmentGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Наименование группы')),
                ('description', models.TextField(blank=True, default='', verbose_name='Описание группы')),
            ],
            options={
                'verbose_name': 'Группа сегментов',
                'verbose_name_plural': 'Группы сегментов',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='segment',
            name='status',
            field=models.CharField(choices=[('В разработке', 'В разработке'), ('Активно', 'Активно'), ('Архив', 'Архив')], default='В разработке', max_length=20, verbose_name='Статус'),
        ),
        migrations.AddField(
            model_name='segment',
            name='supervisor_fallback',
            field=models.CharField(blank=True, default='', help_text='Используется, если ответственного нет в системе', max_length=256, verbose_name='Ответственный (текст)'),
        ),
        migrations.AddField(
            model_name='segment',
            name='segment_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='segments', to='employees.segmentgroup', verbose_name='Группа сегмента'),
        ),
    ]
