# Generated by Django 4.2.8 on 2024-07-19 08:08

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("employees", "0014_alter_diploma_date"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="characteristic",
            name="university",
        ),
        migrations.AlterField(
            model_name="course",
            name="date",
            field=models.DateField(
                blank=True, null=True, verbose_name="Дата прохождения курса"
            ),
        ),
        migrations.CreateModel(
            name="University",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=256, verbose_name="Название")),
                (
                    "file",
                    models.FileField(
                        blank=True,
                        default=None,
                        null=True,
                        upload_to="employees/%(class)s/",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=[
                                    "doc",
                                    "docx",
                                    "xlsx",
                                    "xls",
                                    "csv",
                                    "pdf",
                                    "jpg",
                                    "png",
                                    "jpeg",
                                ]
                            )
                        ],
                        verbose_name="Документ",
                    ),
                ),
                (
                    "date",
                    models.DateField(
                        blank=True,
                        null=True,
                        verbose_name="Дата окончания университета",
                    ),
                ),
                (
                    "characteristic",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to="employees.characteristic",
                        verbose_name="Сотрудник",
                    ),
                ),
            ],
            options={
                "verbose_name": "университет",
                "verbose_name_plural": "университеты",
            },
        ),
    ]
