# Generated by Django 4.2.18 on 2025-05-24 09:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('employees', '0008_competence_is_important_alter_characteristic_about_and_more'),
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PollGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Наименование группы')),
                ('description', models.TextField(blank=True, verbose_name='Описание группы')),
            ],
            options={
                'verbose_name': 'Группа опросов',
                'verbose_name_plural': 'Группы опросов',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Текст вопроса')),
                ('question_type', models.CharField(choices=[('single', 'Один вариант ответа'), ('multiple', 'Несколько вариантов ответа'), ('text', 'Свободный текстовый ответ')], default='single', max_length=10, verbose_name='Тип вопроса')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок вопроса')),
                ('is_required', models.BooleanField(default=True, verbose_name='Обязательный вопрос')),
                ('min_choices', models.PositiveIntegerField(blank=True, null=True, verbose_name='Минимальное количество выбранных вариантов')),
                ('max_choices', models.PositiveIntegerField(blank=True, null=True, verbose_name='Максимальное количество выбранных вариантов')),
            ],
            options={
                'verbose_name': 'Вопрос',
                'verbose_name_plural': 'Вопросы',
                'ordering': ['poll', 'order'],
            },
        ),
        migrations.AlterModelOptions(
            name='choice',
            options={'ordering': ['question', 'order'], 'verbose_name': 'Вариант ответа', 'verbose_name_plural': 'Варианты ответа'},
        ),
        migrations.AlterModelOptions(
            name='poll',
            options={'ordering': ['-created_at'], 'verbose_name': 'Объект "Опрос"', 'verbose_name_plural': 'Объекты "Опросы"'},
        ),
        migrations.RemoveField(
            model_name='choice',
            name='poll',
        ),
        migrations.RemoveField(
            model_name='choice',
            name='voted',
        ),
        migrations.RemoveField(
            model_name='poll',
            name='is_multiple_choice',
        ),
        migrations.RemoveField(
            model_name='poll',
            name='question_text',
        ),
        migrations.AddField(
            model_name='choice',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='Порядок варианта'),
        ),
        migrations.AddField(
            model_name='poll',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authored_polls', to=settings.AUTH_USER_MODEL, verbose_name='Автор опроса'),
        ),
        migrations.AddField(
            model_name='poll',
            name='completion_date',
            field=models.DateTimeField(blank=True, help_text="Дата, после которой опрос автоматически переходит в статус 'Завершен'", null=True, verbose_name='Дата и время завершения опроса'),
        ),
        migrations.AddField(
            model_name='poll',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание опроса'),
        ),
        migrations.AddField(
            model_name='poll',
            name='editors',
            field=models.ManyToManyField(blank=True, related_name='editable_polls', to=settings.AUTH_USER_MODEL, verbose_name='Редакторы опроса (доступ на редактирование)'),
        ),
        migrations.AddField(
            model_name='poll',
            name='is_public',
            field=models.BooleanField(default=False, help_text='Если отмечено, опрос доступен всем пользователям портала, независимо от организации.', verbose_name='Публичный опрос'),
        ),
        migrations.AddField(
            model_name='poll',
            name='name',
            field=models.CharField(max_length=256, null=True, verbose_name='Наименование опроса'),
        ),
        migrations.AddField(
            model_name='poll',
            name='stats_viewers',
            field=models.ManyToManyField(blank=True, related_name='viewable_stats_polls', to=settings.AUTH_USER_MODEL, verbose_name='Просмотр статистики (доступ на просмотр статистики)'),
        ),
        migrations.AddField(
            model_name='poll',
            name='status',
            field=models.CharField(choices=[('draft', 'Черновик'), ('published', 'Опубликован'), ('completed', 'Завершен')], default='draft', max_length=10, verbose_name='Статус опроса'),
        ),
        migrations.AlterField(
            model_name='choice',
            name='choice_text',
            field=models.CharField(max_length=256, verbose_name='Текст варианта ответа'),
        ),
        migrations.AlterField(
            model_name='poll',
            name='organization',
            field=models.ManyToManyField(blank=True, help_text='Если опрос не публичный, он будет доступен сотрудникам указанных организаций.', to='employees.organization', verbose_name='Организация (целевая аудитория опроса)'),
        ),
        migrations.AlterField(
            model_name='poll',
            name='pub_date',
            field=models.DateTimeField(blank=True, help_text='Если установить дату и время в будущем — можно делать отложенные публикации.', null=True, verbose_name='Дата и время публикации'),
        ),
        migrations.CreateModel(
            name='QuestionDependency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dependent_question', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dependency_rule', to='homepage.question', verbose_name='Зависимый вопрос (который показывается/скрывается)')),
                ('trigger_choice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='homepage.choice', verbose_name='Вариант ответа-триггер')),
                ('trigger_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trigger_for_dependencies', to='homepage.question', verbose_name='Вопрос-триггер (от ответа на который зависит показ)')),
            ],
            options={
                'verbose_name': 'Условие отображения вопроса',
                'verbose_name_plural': 'Условия отображения вопросов',
            },
        ),
        migrations.AddField(
            model_name='question',
            name='poll',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='homepage.poll', verbose_name='Опрос'),
        ),
        migrations.CreateModel(
            name='PollSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitted_at', models.DateTimeField(auto_now_add=True, verbose_name='Время отправки')),
                ('poll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='homepage.poll')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='poll_submissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Прохождение опроса',
                'verbose_name_plural': 'Прохождения опросов',
                'unique_together': {('poll', 'user')},
            },
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('free_text_answer', models.TextField(blank=True, null=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='homepage.question')),
                ('selected_choices', models.ManyToManyField(blank=True, related_name='chosen_in_answers', to='homepage.choice')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='homepage.pollsubmission')),
            ],
            options={
                'verbose_name': 'Ответ на вопрос',
                'verbose_name_plural': 'Ответы на вопросы',
            },
        ),
        migrations.AddField(
            model_name='choice',
            name='question',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='homepage.question', verbose_name='Вопрос'),
        ),
        migrations.AddField(
            model_name='poll',
            name='poll_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='polls', to='homepage.pollgroup', verbose_name='Группа опроса'),
        ),
    ]
