# Generated by Django 4.2.18 on 2025-05-24 09:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_pollgroup_question_alter_choice_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questiondependency',
            name='trigger_question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trigger_for_dependencies', to='homepage.question', verbose_name='Вопрос-триггер (от ответа на который зависит показ)'),
        ),
    ]
