# Generated by Django 4.2.18 on 2025-06-10 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0003_alter_questiondependency_trigger_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='custom_choice_text',
            field=models.TextField(blank=True, help_text="Заполняется, если пользователь выбрал опцию 'Другое' и вписал свой вариант.", null=True, verbose_name="Текст своего варианта ответа ('Другое')"),
        ),
        migrations.AddField(
            model_name='question',
            name='allow_custom_answer',
            field=models.BooleanField(default=False, help_text="Если отмечено, пользователь сможет вписать свой вариант (для типов 'Один вариант' и 'Несколько вариантов').", verbose_name="Разрешить свой вариант ответа ('Другое')"),
        ),
    ]
