# Generated by Django 4.2.18 on 2025-07-01 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0004_answer_custom_choice_text_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('single', 'Один вариант ответа'), ('multiple', 'Несколько вариантов ответа'), ('text', 'Свободный текстовый ответ'), ('date', 'Дата'), ('telephone', 'Номер телефона'), ('mail', 'Почта')], default='single', max_length=10, verbose_name='Тип вопроса'),
        ),
    ]
