# Generated by Django 4.2.18 on 2025-07-07 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0006_course_video_videoview_coursevideo_course_videos_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='kind',
            field=models.CharField(choices=[('plain', 'Опрос'), ('form', 'Форма')], default='plain', max_length=10, verbose_name='Тип опроса'),
        ),
    ]
