# Generated by Django 4.2.18 on 2025-07-08 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0007_poll_kind'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='initial_value',
            field=models.CharField(choices=[('None', 'null'), ('fullname', 'Несколько вариантов ответа'), ('position', 'Свободный текстовый ответ'), ('organization', 'Дата'), ('phone', 'Номер телефона'), ('email', 'Почта')], default='None', max_length=15, verbose_name='Предзаполнение'),
        ),
    ]
