# Generated by Django 4.2.18 on 2025-07-10 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0010_alter_question_initial_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='initial_value',
            field=models.CharField(blank=True, choices=[('fullname', 'ФИО'), ('position', 'Должность'), ('organization', 'Организация'), ('phone', 'Номер телефона'), ('email', 'Почта')], default=None, max_length=15, null=True, verbose_name='Предзаполнение'),
        ),
    ]
