# Generated by Django 4.2.8 on 2024-04-24 09:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("homepage", "0012_alter_poll_pub_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="poll",
            name="pub_date",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 4, 24, 12, 2, 52, 911343),
                help_text="Если установить дату и время в будущем — можно делать отложенные публикации.",
                verbose_name="Дата и время публикации",
            ),
        ),
    ]
