# Generated by Django 4.2.18 on 2025-10-15 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0012_news_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poll',
            name='is_public',
        ),
    ]
