# Generated by Django 4.2.18 on 2025-12-17 09:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('homepage', '0012_news_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='SecretSantaSeason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deadline', models.DateTimeField(blank=True, null=True, verbose_name='Крайний срок регистрации/изменений')),
                ('budget', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Бюджет (руб.)')),
                ('is_active', models.BooleanField(default=False, verbose_name='Активен')),
            ],
            options={
                'verbose_name': 'Настройки Тайного Санты',
                'verbose_name_plural': 'Настройки Тайного Санты',
            },
        ),
        migrations.CreateModel(
            name='SecretSantaParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wishes', models.TextField(blank=True, verbose_name='Пожелания')),
                ('address', models.TextField(blank=True, verbose_name='Адрес')),
                ('zip_code', models.IntegerField(blank=True, null=True, verbose_name='Индекс')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='Телефон')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('gift_giver', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='secret_santa_participant', to=settings.AUTH_USER_MODEL, verbose_name='Отправитель подарка')),
                ('gift_receiver', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='secret_santa_receiver', to=settings.AUTH_USER_MODEL, verbose_name='Получатель подарка')),
            ],
            options={
                'verbose_name': 'Участник Тайного Санты',
                'verbose_name_plural': 'Участники Тайного Санты',
            },
        ),
    ]
