# Generated by Django 4.2.18 on 2025-12-25 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0014_secretsantaseason_secretsantaparticipant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='pub_date',
            field=models.DateTimeField(blank=True, default=None, help_text='Если установить дату и время в будущем — можно делать отложенные публикации.', null=True, verbose_name='Дата и время публикации'),
        ),
    ]
