# django.conf
location ${DJANGO_PREFIX}/ {
    proxy_pass http://django:${DJANGO_PORT};
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_set_header SCRIPT_NAME ${DJANGO_PREFIX}/;

    # Handle large file uploads
    client_max_body_size 512M;
    proxy_read_timeout 300s;
}

location ${DJANGO_PREFIX}/media/ {
    alias /var/www/django/media/;
    expires 30d;
    add_header Cache-Control "public, max-age=2592000$asset_immutable";
    access_log off;
}
