name: kp-nginx

networks:
  kp:
    external: true
    name: $NETWORK_NAME

services:
  nginx:
    image: nginx:1.27-alpine
    ports:
      - 30080:80
    networks:
      - kp
    volumes:
      - ./main.conf:/etc/nginx/nginx.conf:ro
      # - ./main.conf:/etc/nginx/conf.d/default.conf:ro
      - ./templates/:/etc/nginx/templates/:ro
      - ../django/media/:/var/www/django/media/:ro
    environment:
      NGINX_ENVSUBST_TEMPLATE_SUFFIX: ".tmpl.conf"
      DJANGO_PREFIX: $DJANGO_PREFIX
      DJANGO_PORT: $DJANGO_PORT
