services:
  liferay:
    image: liferay/portal:7.0.6-ga7
    ports:
      - 8080:8080
    volumes:
      # Copy .war here to deploy it.
      - ./deploy:/mnt/liferay/deploy
      - ./portal-ext.properties:/opt/liferay/portal-ext.properties
    environment:
      LIFERAY_JDBC_PERIOD_DEFAULT_PERIOD_URL: jdbc:postgresql://db:5432/${POSTGRES_DB}
      LIFERAY_JDBC_PERIOD_DEFAULT_PERIOD_USERNAME: "${POSTGRES_USER}"
      LIFERAY_JDBC_PERIOD_DEFAULT_PERIOD_PASSWORD: "${POSTGRES_PASSWORD}"
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:13.16-alpine
    environment:
      POSTGRES_DB: "${POSTGRES_DB}"
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
    volumes:
      - ./data:/var/lib/postgresql/data
    healthcheck:
      test:
        ["CMD", "pg_isready", "-U", "${POSTGRES_USER}", "-d", "${POSTGRES_DB}"]
      timeout: 3s
      interval: 60s
      start_interval: 3s
      start_period: 60s
