# Generated by Django 4.2.8 on 2024-04-03 09:27

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AbstractWithPhotoNameModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=256, verbose_name="Название")),
                (
                    "image",
                    models.ImageField(
                        default=None,
                        null=True,
                        upload_to="employees/%(class)s/",
                        verbose_name="Картинка",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Characteristic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "university",
                    models.CharField(max_length=256, verbose_name="Университет"),
                ),
                ("diploma", models.CharField(max_length=256, verbose_name="Диплом")),
                ("experience", models.PositiveSmallIntegerField(verbose_name="Стаж")),
            ],
        ),
        migrations.CreateModel(
            name="Employee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "fio",
                    models.CharField(
                        max_length=256, verbose_name="Фамилия Имя Отчество"
                    ),
                ),
                ("birth_date", models.DateTimeField(verbose_name="Дата рождения")),
                ("email", models.EmailField(max_length=254, verbose_name="Почта")),
                (
                    "telephone_number",
                    phonenumber_field.modelfields.PhoneNumberField(
                        max_length=128,
                        region=None,
                        unique=True,
                        verbose_name="Номер телефона",
                    ),
                ),
                (
                    "job_title",
                    models.CharField(max_length=256, verbose_name="Должность"),
                ),
                (
                    "class_rank",
                    models.CharField(max_length=256, verbose_name="Классный чин"),
                ),
                (
                    "characteristic",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="employee",
                        to="employees.characteristic",
                        verbose_name="Характеристика сотрудника",
                    ),
                ),
            ],
            options={
                "verbose_name": "Сотрудник",
                "verbose_name_plural": "Сотрудники",
            },
        ),
        migrations.CreateModel(
            name="Organization",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=256, verbose_name="Название")),
                (
                    "address",
                    models.CharField(max_length=256, verbose_name="Адрес организации"),
                ),
                (
                    "structural_division",
                    models.CharField(
                        max_length=256, verbose_name="Структурное подразделение"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Conference",
            fields=[
                (
                    "abstractwithphotonamemodel_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="employees.abstractwithphotonamemodel",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("employees.abstractwithphotonamemodel",),
        ),
        migrations.CreateModel(
            name="Hobby",
            fields=[
                (
                    "abstractwithphotonamemodel_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="employees.abstractwithphotonamemodel",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("employees.abstractwithphotonamemodel",),
        ),
        migrations.CreateModel(
            name="Performance",
            fields=[
                (
                    "abstractwithphotonamemodel_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="employees.abstractwithphotonamemodel",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("employees.abstractwithphotonamemodel",),
        ),
        migrations.CreateModel(
            name="Reward",
            fields=[
                (
                    "abstractwithphotonamemodel_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="employees.abstractwithphotonamemodel",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("employees.abstractwithphotonamemodel",),
        ),
        migrations.CreateModel(
            name="Sport",
            fields=[
                (
                    "abstractwithphotonamemodel_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="employees.abstractwithphotonamemodel",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("employees.abstractwithphotonamemodel",),
        ),
        migrations.CreateModel(
            name="Training",
            fields=[
                (
                    "abstractwithphotonamemodel_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="employees.abstractwithphotonamemodel",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("employees.abstractwithphotonamemodel",),
        ),
        migrations.CreateModel(
            name="Victory",
            fields=[
                (
                    "abstractwithphotonamemodel_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="employees.abstractwithphotonamemodel",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("employees.abstractwithphotonamemodel",),
        ),
        migrations.CreateModel(
            name="Volunteer",
            fields=[
                (
                    "abstractwithphotonamemodel_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="employees.abstractwithphotonamemodel",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("employees.abstractwithphotonamemodel",),
        ),
        migrations.CreateModel(
            name="Rating",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rate",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(5),
                        ]
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rated",
                        to="employees.employee",
                        verbose_name="Оцениваемый сотрудник",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rates",
                        to="employees.employee",
                        verbose_name="Оценивающий сотрудник",
                    ),
                ),
            ],
            options={
                "verbose_name": "Оценка",
                "verbose_name_plural": "Оценки",
            },
        ),
        migrations.AddField(
            model_name="employee",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="employees",
                to="employees.organization",
                verbose_name="Организация",
            ),
        ),
        migrations.AddField(
            model_name="employee",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=256, verbose_name="Название")),
                ("date", models.DateTimeField(verbose_name="Дата прохождения курса")),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s",
                        to="employees.employee",
                        verbose_name="Сотрудник",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Competence",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=256, verbose_name="Название")),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s",
                        to="employees.employee",
                        verbose_name="Сотрудник",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Career",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date",
                    models.DateTimeField(verbose_name="Дата вступления в должность"),
                ),
                ("title", models.CharField(max_length=256, verbose_name="Должность")),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="career",
                        to="employees.employee",
                        verbose_name="Сотрудник",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="abstractwithphotonamemodel",
            name="employee",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s",
                to="employees.employee",
                verbose_name="Сотрудник",
            ),
        ),
        migrations.AddConstraint(
            model_name="rating",
            constraint=models.CheckConstraint(
                check=models.Q(("rate__range", (0, 5))), name="valid_rate"
            ),
        ),
        migrations.AddConstraint(
            model_name="rating",
            constraint=models.UniqueConstraint(
                fields=("user", "employee"), name="rating_once"
            ),
        ),
    ]
