# Generated by Django 4.2.8 on 2024-04-03 09:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("employees", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="birth_date",
            field=models.DateField(verbose_name="Дата рождения"),
        ),
    ]
