# Generated by Django 4.2.8 on 2024-04-03 09:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("employees", "0002_alter_employee_birth_date"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="employee",
            name="characteristic",
        ),
        migrations.AddField(
            model_name="characteristic",
            name="employee",
            field=models.OneToOneField(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="characteristic",
                to="employees.employee",
            ),
            preserve_default=False,
        ),
    ]
