# Generated by Django 4.2.8 on 2024-04-08 17:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        (
            "employees",
            "0004_alter_career_options_alter_characteristic_options_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="characteristic",
            name="about",
            field=models.TextField(blank=True, null=True, verbose_name="Обо мне"),
        ),
        migrations.AlterField(
            model_name="characteristic",
            name="diploma",
            field=models.CharField(
                blank=True, max_length=256, null=True, verbose_name="Диплом"
            ),
        ),
        migrations.AlterField(
            model_name="characteristic",
            name="employee",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="characteristic",
                to="employees.employee",
                verbose_name="Сотрудник",
            ),
        ),
        migrations.AlterField(
            model_name="characteristic",
            name="experience",
            field=models.PositiveSmallIntegerField(
                blank=True, null=True, verbose_name="Стаж работы (лет)"
            ),
        ),
        migrations.AlterField(
            model_name="characteristic",
            name="university",
            field=models.CharField(
                blank=True, max_length=256, null=True, verbose_name="Университет"
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="status",
            field=models.CharField(
                choices=[
                    ("В отпуске", "В отпуске"),
                    ("В командировке", "В командировке"),
                    ("На больничном", "На больничном"),
                    ("На рабочем месте", "На рабочем месте"),
                    ("Нет на месте", "Нет на месте"),
                ],
                default="На рабочем месте",
                max_length=16,
                verbose_name="Статус",
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="information",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
