# Generated by Django 4.2.8 on 2024-06-10 07:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        (
            "employees",
            "0011_alter_characteristic_avatar_alter_conference_image_and_more",
        ),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="rating",
            name="valid_rate",
        ),
        migrations.AlterField(
            model_name="conference",
            name="image",
            field=models.ImageField(
                blank=True,
                default=None,
                null=True,
                upload_to="employees/%(class)s/",
                verbose_name="Картинка",
            ),
        ),
        migrations.AlterField(
            model_name="hobby",
            name="image",
            field=models.ImageField(
                blank=True,
                default=None,
                null=True,
                upload_to="employees/%(class)s/",
                verbose_name="Картинка",
            ),
        ),
        migrations.AlterField(
            model_name="performance",
            name="image",
            field=models.ImageField(
                blank=True,
                default=None,
                null=True,
                upload_to="employees/%(class)s/",
                verbose_name="Картинка",
            ),
        ),
        migrations.AlterField(
            model_name="rating",
            name="employee",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="rated",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Кого оценивают",
            ),
        ),
        migrations.AlterField(
            model_name="rating",
            name="rate",
            field=models.PositiveSmallIntegerField(
                choices=[(1, "1"), (2, "2"), (3, "3"), (4, "4"), (5, "5")]
            ),
        ),
        migrations.AlterField(
            model_name="rating",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="rates",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Кто оценивает",
            ),
        ),
        migrations.AlterField(
            model_name="reward",
            name="image",
            field=models.ImageField(
                blank=True,
                default=None,
                null=True,
                upload_to="employees/%(class)s/",
                verbose_name="Картинка",
            ),
        ),
        migrations.AlterField(
            model_name="sport",
            name="image",
            field=models.ImageField(
                blank=True,
                default=None,
                null=True,
                upload_to="employees/%(class)s/",
                verbose_name="Картинка",
            ),
        ),
        migrations.AlterField(
            model_name="training",
            name="image",
            field=models.ImageField(
                blank=True,
                default=None,
                null=True,
                upload_to="employees/%(class)s/",
                verbose_name="Картинка",
            ),
        ),
        migrations.AlterField(
            model_name="victory",
            name="image",
            field=models.ImageField(
                blank=True,
                default=None,
                null=True,
                upload_to="employees/%(class)s/",
                verbose_name="Картинка",
            ),
        ),
        migrations.AlterField(
            model_name="volunteer",
            name="image",
            field=models.ImageField(
                blank=True,
                default=None,
                null=True,
                upload_to="employees/%(class)s/",
                verbose_name="Картинка",
            ),
        ),
    ]
