# Generated by Django 4.2.8 on 2024-07-08 07:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("employees", "0013_rename_date_career_date_start_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="diploma",
            name="date",
            field=models.DateField(
                blank=True, null=True, verbose_name="Дата получения диплома"
            ),
        ),
    ]
