services:
  django:
    build: ../django/

    # Resolve local domains (on a VPN).
    network_mode: host
    environment:
      DJANGO_PORT: "${BACKEND_PORT}"
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_DB: "${POSTGRES_DB}"
      POSTGRES_DB_LIFERAY: "${POSTGRES_DB_LIFERAY}"
      DB_HOST: "${DB_HOST}"
      SECRET_KEY: "${SECRET_KEY}"
      ALLOWED_HOSTS: "${HOSTNAME}"
      ALLOWED_ORIGINS: "${AUTHORITY}"
      DEBUG: 0
      PROD: 1
      CHALLENGE_URL: "${CHALLENGE_URL}"
      SCRIPT_NAME: "${BACKEND_PREFIX}"
    volumes:
      - ./volumes/media:/media
