services:
  django:
    build: ../django/
    command: >
      sh -c "python manage.py makemigrations &&
        python manage.py migrate --noinput &&
        python manage.py collectstatic --noinput &&
        gunicorn --bind 0.0.0.0:8000 korp_portal.wsgi"
    environment:
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_DB: "${POSTGRES_DB}"
      DB_HOST: "${DB_HOST}"
      SECRET_KEY: "${SECRET_KEY}"
      ALLOWED_HOSTS: "${HOSTNAME}"
      ALLOWED_ORIGINS: "${AUTHORITY}"
      DEBUG: 0
      LDAP_PASSWORD: "${LDAP_PASSWORD}"
      LDAP_URI: "${LDAP_URI}"
      LDAP_USER: "${LDAP_USER}"
      LDAP_ROOT: "${LDAP_ROOT}"
      CHALLENGE_URL: "${CHALLENGE_URL}"
      GROUP_USER: "${DJANGO_GROUP_USER}"
      GROUP_ADMIN: "${DJANGO_GROUP_ADMIN}"
    volumes:
      - ./volumes/media:/media
    ports:
      - "${BACKEND_PORT}:80"
